### ISSUE TITLE
Argument 2 passed to Psr\Log\AbstractLogger::info() must be of the type array, null given

### ISSUE THREAD

**Issue by stephangrass** [pagemachine/svconnector_xls#18]
Hi,
when trying to test the connection in the Connector Services Sandbox, I get the error "Argument 2 passed to Psr \ Log \ AbstractLogger :: info () must be of the type array, null given, called in /Users/stephangrass/Documents/_Webs_/thiele.de /typo3/www/typo3conf/ext/svconnector_xls/Classes/Service/XlsxConnector.php on line 37 "

I only entered the parameter filename = path to xlsx as a parameter

**Comment by stephangrass** [comment]
Ok. The configuration has to be in json-format.

{
  "filename" : "path to xlsx"
}

**Comment by mbrodala** [comment]
Glad you got the issue resolved. What is the "sandbox" you refer to here?

**Comment by stephangrass** [comment]
I meant the Connenctors test module from the External Import extension.
But one more question: can the pid also be set in the import files?
I think that the question is more about the External Import extension, but maybe you know that ...

**Comment by mbrodala** [comment]
OK, then I know what you mean. ;-)

And yes, you can set the `pid` in the `general` section:

https://docs.typo3.org/p/cobweb/external_import/master/en-us/Administration/GeneralTca/Index.html#pid

**Comment by stephangrass** [comment]
I know that you can set the pid in the general section. I would like to pass the pid in the import file. So for every data record to be imported.

**Comment by mbrodala** [comment]
In that case you could try to set up a mapping for the `pid` column. Not sure if this will be overwritten though.

In any case we should switch to the TYPO3 Slack for further questions. ;-)

**Comment by stephangrass** [comment]
Thanks
