### ISSUE TITLE
Change in connector service registration

### ISSUE THREAD

**Issue by fsuter** [pagemachine/svconnector_xls#64]
Since services have been deprecated and finally dropped in TYPO3 12, "svconnector" now comes with its own registration mechanism for Connector Services. This is a complete breaking change and existing services need to be adapted. Please see https://docs.typo3.org/p/cobweb/svconnector/main/en-us/Installation/Index.html#updating-to-5-0-0

**Comment by mbrodala** [comment]
Thanks for the hint. It looks like this will need a bit of fiddling to continue support for 2 TYPO3 versions in parallel, otherwise we'd need to drop support for TYPO3v11.

**Comment by fsuter** [comment]
The change is perfectly compatible with TYPO3 11.  I mentioned v12 only because the complete removal of the services architecture was the reason for the change. Current versions of all connectors support 11 and 12.

**Comment by mbrodala** [comment]
Thanks for the hint, I'll have a closer look.

**Comment by mbrodala** [comment]
I did update almost everything but one thing currently fails:

> PHP Fatal error:  Type of            
> Pagemachine\SvconnectorXls\Service\AbstractConnector::$extensionKey must  
> not be defined (as in class Cobweb\Svconnector\Service\ConnectorBase) in  
> /usr/src/app/Classes/Service/AbstractConnector.php on line 14

This happens when adding the native `string` type hint to the `$extensionKey` property and using Svconnector 4.x.

See https://github.com/pagemachine/svconnector_xls/actions/runs/4231009209/jobs/7349006069#step:3:459

**Comment by mbrodala** [comment]
And here goes the next one:

> PHP Fatal error:  Declaration of  
> Pagemachine\SvconnectorXls\Service\AbstractConnector::fetchRaw(array   
> $parameters = Array) must be compatible with                           
> Cobweb\Svconnector\Service\ConnectorBase::fetchRaw($parameters) in     
> /usr/src/app/Classes/Service/AbstractConnector.php on line 38

See https://github.com/pagemachine/svconnector_xls/actions/runs/4231192401/jobs/7349406351#step:3:459

So, as I assumed, it is impossible to easily support Connector Services 3.x/4.x and 5.x at the same time. We'll need a whole different class structure with code duplication instead. :-(

**Comment by mbrodala** [comment]
Dropped that now and did a hard switch to 5.x. See https://github.com/pagemachine/svconnector_xls/pull/66
